-- EC_IT143_W4.2_museums_s2_jp.sql
-- Step 2: Begin creating an answer
-- To answer this question, I will use the Museums_UK table.
-- I plan to group by the city name and find the minimum Year_opened.
-- Then I will join this result back to the main table to get the museum name.
